baseurl = "https://mullet1989.github.io/herculeswimbledonac/"
title = "Hercules Wimbledon AC"
languageCode = "en-us"
paginate = "10" # Number of posts per page
theme = "mainroad"
disqusShortname = "" # Enable comments by entering your Disqus shortname
googleAnalytics = "" # Enable Google Analytics by entering your tracking id
publishDir = "docs"
sectionPagesMenu = "main"


[Author]
    name = "Benjamin Toomer"
    bio = "I am a runner"
    avatar = "img/avatar.jpg"


[Params]
    baseurl = "herculeswimbledonac/"
    subtitle = "We are the best team in Surrey" # Subtitle of your site
    description = "Homepage of Hercules Wimbledon AC" # Description of your site
    opengraph = true
    readmore = false # Show "Read more" button in list if true
    leftsidebar = false # Move sidebar to the left side if true
    authorbox = true
    post_navigation = true
    postSections = ["posts", "news"] # the section pages to show on home page and the "Recent articles" widget
    #postSections = ["blog", "news"] # alternative that shows more than one section's pages
    #dateformat = "2006-01-02" # change the format of dates


[Params.widgets]
    search = true # Enable "Search" widget
    recent_articles = true # Enable "Recent articles" widget
    recent_articles_num = 10 # Set the number of articles in the "Recent articles" widget
    categories = true # Enable "Categories" widget
    tags = true # Enable "Tags" widget
    tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)

    # Enable "Social" widget, if any of "social_*" set a value
    social_facebook = "HerculesWimbledon"
    social_twitter = "HWimbledon"
    social_linkedin = ""
    #social_github = ""
    social_email = "info@herculeswimbledonac.org.uk"

[[menu.main]]
    name = "news"
    pre = "<i class='fa fa-newspaper-o'></i>"
    url = "/news"
[[menu.main]]
    name = "posts"
    pre = "<i class='fa fa-heart'></i>"
    url = "/posts"
[[menu.main]]
    name = "results"
    pre = "<i class='fa fa-road'></i>"
    url = "/results"